![Cartoon of telecom customers](IMG_8811.png)


The telecommunications (telecom) sector in India is rapidly changing, with more and more telecom businesses being created and many customers deciding to switch between providers. "Churn" refers to the process where customers or subscribers stop using a company's services or products. Understanding the factors that influence keeping a customer as a client in predicting churn is crucial for telecom companies to enhance their service quality and customer satisfaction. As the data scientist on this project, you aim to explore the intricate dynamics of customer behavior and demographics in the Indian telecom sector in predicting customer churn, utilizing two comprehensive datasets from four major telecom partners: Airtel, Reliance Jio, Vodafone, and BSNL:

- `telecom_demographics.csv` contains information related to Indian customer demographics:

| Variable             | Description                                      |
|----------------------|--------------------------------------------------|
| `customer_id `         | Unique identifier for each customer.             |
| `telecom_partner `     | The telecom partner associated with the customer.|
| `gender `              | The gender of the customer.                      |
| `age `                 | The age of the customer.                         |
| `state`                | The Indian state in which the customer is located.|
| `city`                 | The city in which the customer is located.       |
| `pincode`              | The pincode of the customer's location.          |
| `registration_event` | When the customer registered with the telecom partner.|
| `num_dependents`      | The number of dependents (e.g., children) the customer has.|
| `estimated_salary`     | The customer's estimated salary.                 |

- `telecom_usage` contains information about the usage patterns of Indian customers:

| Variable   | Description                                                  |
|------------|--------------------------------------------------------------|
| `customer_id` | Unique identifier for each customer.                         |
| `calls_made` | The number of calls made by the customer.                    |
| `sms_sent`   | The number of SMS messages sent by the customer.             |
| `data_used`  | The amount of data used by the customer.                     |
| `churn`    | Binary variable indicating whether the customer has churned or not (1 = churned, 0 = not churned).|


In [283]:
# Import libraries and methods/functions
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Start your code here!

In [284]:
# Load the CSV files into separate DataFrames
demographics_df = pd.read_csv('telecom_demographics.csv')
usage_df = pd.read_csv('telecom_usage.csv')

In [285]:
demographics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   customer_id         6500 non-null   int64 
 1   telecom_partner     6500 non-null   object
 2   gender              6500 non-null   object
 3   age                 6500 non-null   int64 
 4   state               6500 non-null   object
 5   city                6500 non-null   object
 6   pincode             6500 non-null   int64 
 7   registration_event  6500 non-null   object
 8   num_dependents      6500 non-null   int64 
 9   estimated_salary    6500 non-null   int64 
dtypes: int64(5), object(5)
memory usage: 507.9+ KB


In [286]:
demographics_df.head()

customer_id telecom_partner  ... num_dependents  estimated_salary
0        15169          Airtel  ...              4             85979
1       149207          Airtel  ...              0             69445
2       148119          Airtel  ...              2             75949
3       187288    Reliance Jio  ...              3             34272
4        14016        Vodafone  ...              4             34157

[5 rows x 10 columns]

In [287]:
usage_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  6500 non-null   int64
 1   calls_made   6500 non-null   int64
 2   sms_sent     6500 non-null   int64
 3   data_used    6500 non-null   int64
 4   churn        6500 non-null   int64
dtypes: int64(5)
memory usage: 254.0 KB


In [288]:
usage_df.head()

customer_id  calls_made  sms_sent  data_used  churn
0        15169          75        21       4532      1
1       149207          35        38        723      1
2       148119          70        47       4688      1
3       187288          95        32      10241      1
4        14016          66        23       5246      1

In [289]:
# Merge both datasets on 'customer_id'
churn_df = pd.merge(demographics_df, usage_df, on='customer_id')

churn_df.head()

customer_id telecom_partner gender  ...  sms_sent data_used churn
0        15169          Airtel      F  ...        21      4532     1
1       149207          Airtel      F  ...        38       723     1
2       148119          Airtel      F  ...        47      4688     1
3       187288    Reliance Jio      M  ...        32     10241     1
4        14016        Vodafone      M  ...        23      5246     1

[5 rows x 14 columns]

In [290]:
# Identify churn rate
churn_rate = churn_df['churn'].value_counts() / len(churn_df)
print(churn_rate)

0    0.799538
1    0.200462
Name: churn, dtype: float64


In [291]:
churn_df.isna().sum()

customer_id           0
telecom_partner       0
gender                0
age                   0
state                 0
city                  0
pincode               0
registration_event    0
num_dependents        0
estimated_salary      0
calls_made            0
sms_sent              0
data_used             0
churn                 0
dtype: int64

In [292]:
print(churn_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6500 entries, 0 to 6499
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   customer_id         6500 non-null   int64 
 1   telecom_partner     6500 non-null   object
 2   gender              6500 non-null   object
 3   age                 6500 non-null   int64 
 4   state               6500 non-null   object
 5   city                6500 non-null   object
 6   pincode             6500 non-null   int64 
 7   registration_event  6500 non-null   object
 8   num_dependents      6500 non-null   int64 
 9   estimated_salary    6500 non-null   int64 
 10  calls_made          6500 non-null   int64 
 11  sms_sent            6500 non-null   int64 
 12  data_used           6500 non-null   int64 
 13  churn               6500 non-null   int64 
dtypes: int64(9), object(5)
memory usage: 761.7+ KB
None


In [293]:
churn_df.churn.value_counts()

0    5197
1    1303
Name: churn, dtype: int64

In [294]:
# Converting categorical variables into numerical variables
churn_df = pd.get_dummies(churn_df, columns=['telecom_partner', 'gender', 'state', 'city', 'registration_event'])

churn_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6500 entries, 0 to 6499
Columns: 1265 entries, customer_id to registration_event_2023-05-03
dtypes: int64(9), uint8(1256)
memory usage: 8.3 MB


In [295]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler() 

# scale numerical features of churn_df
numerical_features = churn_df.select_dtypes(include=['int64', 'float64', 'uint8']).columns

In [296]:
# Define the features and target variable
features = churn_df.drop(['customer_id','churn'], axis=1)
target = churn_df['churn']

In [297]:
# Scale the features
features_scaled = scaler.fit_transform(features)

# Show the scaled features along with the date column
features_scaled

array([[-1.22296979,  0.45493603,  1.43653887, ..., -0.04117252,
        -0.03283419, -0.02774568],
       [ 1.6963038 , -0.90419473, -1.41134604, ..., -0.04117252,
        -0.03283419, -0.02774568],
       [ 0.47993981,  0.00372937,  0.01259641, ..., -0.04117252,
        -0.03283419, -0.02774568],
       ...,
       [-1.64869719, -1.5268359 , -1.41134604, ..., -0.04117252,
        -0.03283419, -0.02774568],
       [-1.22296979,  0.89731466,  0.72456764, ..., -0.04117252,
        -0.03283419, -0.02774568],
       [-1.64869719,  1.42210486,  0.72456764, ..., -0.04117252,
        -0.03283419, -0.02774568]])

In [298]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_scaled, target, test_size=0.20, random_state=42)

# Display the shapes of the train and test sets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5200, 1263), (1300, 1263), (5200,), (1300,))

In [299]:
logreg = LogisticRegression(random_state=42)
logreg.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [300]:
logreg_pred = logreg.predict(X_test)

In [301]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [302]:
rf_pred = rf.predict(X_test)

In [303]:
# Create the classification report and confusion matrix for the logistic regression model
class_rep_logreg = classification_report(y_test, logreg_pred)
confusion_matrix_logreg = confusion_matrix(y_test, logreg_pred)

print("Logistic Regression: \n", class_rep_logreg)
print("Logistic Regression: \n", confusion_matrix_logreg)

Logistic Regression: 
               precision    recall  f1-score   support

           0       0.79      0.90      0.84      1027
           1       0.21      0.10      0.14       273

    accuracy                           0.73      1300
   macro avg       0.50      0.50      0.49      1300
weighted avg       0.67      0.73      0.69      1300

Logistic Regression: 
 [[920 107]
 [245  28]]


In [304]:
# to get accuracy score only
logreg_acc = accuracy_score(y_test, logreg_pred)
logreg_acc

0.7292307692307692

In [305]:
# Create the classification report for the random forest model
class_rep_forest = classification_report(y_test, rf_pred)
confusion_matrix_forest = confusion_matrix(y_test, rf_pred)

print("Random Forest: \n", class_rep_forest)
print("Random Forest: \n", confusion_matrix_forest)

Random Forest: 
               precision    recall  f1-score   support

           0       0.79      1.00      0.88      1027
           1       0.00      0.00      0.00       273

    accuracy                           0.79      1300
   macro avg       0.39      0.50      0.44      1300
weighted avg       0.62      0.79      0.70      1300

Random Forest: 
 [[1026    1]
 [ 273    0]]


In [306]:
# To get accuracy score only
forest_acc = accuracy_score(y_test, rf_pred)
forest_acc

0.7892307692307692

In [307]:
# Which accuracy score is higher? Logistic Regression or RandomForest
higher_accuracy = "RandomForest"